travis:
  secure:
    BINSTAR_TOKEN: GQhdibY6TDvhHTVxb9yuBgVs30uWMsN7X2Rk/OxU7tVjgKXfORgS4xLL5U7x9bUq2umVTdnLVW7j4tFhdkgxRgHbpNoqmpAnSJB+/hBMfr3LYp15rCpij5Z/WWWUdEnEN2nwVp584UxcM3v5GtBn0B8c+BCVu63qZ7BPkaAtwS1mu521XDFAV01IemK8+QWgHGbwk6u47en3ZvAkAKFfMD3JzL3TF72H7w07EJdIZ0Rp+bRn+z1TLyPricjXg4C3xzw6FUCqGW10K2XoYWbY0WlR2Sh7t0Cf80DqOFXF4B1F2Mi6a5vIy81dR5QaifBcB3BBw54md8YWyMM7AxAi3HTYjlo16C/XX5OyRB2gz/tPRb+sU66n9MoYl6/fHlQIQqFXEyNHKSlBZHgVXp+Bjgg996GfA9U/iutGBgbF8+RRrLfAHfuSb28sAb7pUqJD4HO6A3uvJ1TatW7gVisw74iVoh8mplaLwiHYQoa9ymEBXxAWJd1SIhf8Kiq6YKpoceAvH8uiuSvP22y7e0P0K4vfSIs61h+NOz6/iyMJw8FHNUA0aXK/Ab++RQ7sZesyGl/eWfHcxIAbdwCu3nJ9kVugtmK52Eot7tAuViI0m0lIIVJZlcS3ylk3slWS8xoBCDlPhZo/VrSRVR8iQg8neGmW76GZH+HnsvexESTudxw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
